### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by softius** [scrum2b/scrum2b#151]
Is this project still maintained?

There are two pull requests pending that I am interested to merge (#143 and #148). Also I've noticed that the domains mentioned in README file are no longer available i.e. www.scrum2b.com and www.scrumtobe.com

**Comment by haibt** [comment]
Hi, I will personally maintain the project. I will update the new branch 3.0-stable with the ideas from 2.1-stable, but will reuse the jQuery (Not AngularJS) like the original versions before.
Hope you could see it is interesting.

**Comment by softius** [comment]
That's great thanks for getting back.
