### ISSUE TITLE
Could you give me an demo accout on http://scrum2b.herokuapp.com/login

### ISSUE THREAD

**Issue by archonwang** [scrum2b/scrum2b#159]
@scrum2b-admin 

Could you give me an demo accout on http://scrum2b.herokuapp.com/login

I can not use the demo/demo1234 on the site: 
>http://scrum2b.herokuapp.com/projects/scrum2b-demo

**Comment by gktrainer** [comment]
demo/demo123

**Comment by archonwang** [comment]
@gktrainer ,
Thanks.
