### ISSUE TITLE
Issue Statuses are not displayed in columns

### ISSUE THREAD

**Issue by d-alves** [scrum2b/scrum2b#164]
Hi, I just added Scrum2b to Redmine, but it's different from the screens available at github.com/scrum2b/scrum2b/wiki/Screens.
Here's how it looks:

![scrum2b](https://user-images.githubusercontent.com/20925791/42523157-46c7b0bc-8443-11e8-9168-42fc5902f492.png)

Is there something I forgot to do? Could you help me, please?
Thanks!

**Comment by larifarissa** [comment]
Since you closed this, I assume you found an answer? Could you share it with me?
