### ISSUE TITLE
Need help for scrum2b plugin with Redmine 2.4.1 version

### ISSUE THREAD

**Issue by m1kl** [scrum2b/scrum2b#83]
Hi,

Firstable I want to thank you for this great project. So far, the best I found related to scrum methodology.

I am facing some issues with Scrum2b (version 2.0) plugin with Redmine 2.4.1. I was able to install sucessfully the plugin. But the following features are not working:
- Drag and Drop of issues in the scrumboard to change state
- I am not able to see the slider to set the completion percentage
- When clicking on the comments and attach icons I am only able to see issue details in a dialog

Am I missing some configuration or did I miss some dependencies installation?

I attached some screenshots to show you what I am getting.

![screen shot 2014-01-12 at 20 11 33](https://f.cloud.github.com/assets/2827671/1897040/d302cfb8-7bc8-11e3-8ede-beb6ce916615.png)
![screen shot 2014-01-12 at 20 11 42](https://f.cloud.github.com/assets/2827671/1897041/d302e73c-7bc8-11e3-8e87-0a299545b0ce.png)
![screen shot 2014-01-12 at 20 12 01](https://f.cloud.github.com/assets/2827671/1897042/d3057164-7bc8-11e3-9016-a7e96cc296d6.png)

**Comment by soumya2223** [comment]
## Issues appear 3 times each in Scrum2B board
hi
I'm testing Scrum2B in a fresh installation of Redmine 2.5.0 (via Bitnami Stacks) and I'm having some trouble.

Every issue I create is showed in Scrum2B three times, one in each category: "New Items", "In Progress" and "Completed". The issue itself is not tripled.
![Screenshot from 2020-03-07 12-44-44](https://user-images.githubusercontent.com/54974563/76138895-3d0c2b00-6071-11ea-9ea1-a39f89c4082a.png)
